# Generated by Django 6.0.1 on 2026-01-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Снимите галочку, чтобы скрыть публикацию.",
                        verbose_name="Опубликовано",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Добавлено"),
                ),
                ("name", models.CharField(max_length=15, verbose_name="Название")),
                ("slug", models.SlugField(unique=True, verbose_name="Идентификатор")),
            ],
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Снимите галочку, чтобы скрыть публикацию.",
                        verbose_name="Опубликовано",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Добавлено"),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Заголовок")),
                (
                    "subtitle",
                    models.CharField(max_length=100, verbose_name="Подзаголовок"),
                ),
                ("text", models.TextField(verbose_name="Текст статьи")),
                ("slug", models.SlugField(unique=True, verbose_name="Идентификатор")),
                (
                    "pub_date",
                    models.DateTimeField(verbose_name="Дата и время публикации"),
                ),
            ],
            options={
                "verbose_name": "пост",
                "verbose_name_plural": "Посты",
                "ordering": ("-pub_date",),
                "default_related_name": "posts_list",
            },
        ),
    ]
