# Generated by Django 5.0.2 on 2026-02-04 09:45

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0010_alter_category_options_alter_category_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="pub_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 2, 4, 9, 45, 48, 976963, tzinfo=datetime.UTC
                ),
                verbose_name="Дата и время публикации",
            ),
        ),
    ]
